version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  inventory:
    image: inventory
    container_name: inventory
    environment:
      PG_PASSWORD: testpassword
      PG_HOST: db
      PG_USERNAME: testuser
      POSTGRES_DB: ecommerce
    ports:
      - "8000:8000"
    depends_on:
      - db

  product:
    image: product
    container_name: product
    environment:
      PG_PASSWORD: testpassword
      PG_HOST: db
      PG_USERNAME: testuser
      POSTGRES_DB: ecommerce
    ports:
      - "8001:8000"
    depends_on:
      - db

  order:
    image: order
    container_name: order
    environment:
      PG_PASSWORD: testpassword
      PG_HOST: db
      PG_USERNAME: testuser
      POSTGRES_DB: ecommerce
    ports:
      - "8002:8000"
    depends_on:
      - db

volumes:
  postgres-data:
