apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: orders
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: rds-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: PG_HOST
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_HOST
    - secretKey: PG_PASSWORD
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_PASSWORD
    - secretKey: PG_USERNAME
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_USERNAME
    - secretKey: PG_DATABASE
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_DATABASE
    - secretKey: PRODUCT_SERVICE_URL
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PRODUCT_SERVICE_URL
    - secretKey: INVENTORY_SERVICE_URL
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: INVENTORY_SERVICE_URL
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: inventory
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: rds-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: PG_HOST
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_HOST
    - secretKey: PG_PASSWORD
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_PASSWORD
    - secretKey: PG_USERNAME
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_USERNAME
    - secretKey: PG_DATABASE
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_DATABASE
    - secretKey: PRODUCT_SERVICE_URL
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PRODUCT_SERVICE_URL
    - secretKey: ORDER_SERVICE_URL
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: ORDER_SERVICE_URL
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: produdct
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: rds-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: PG_HOST
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_HOST
    - secretKey: PG_PASSWORD
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_PASSWORD
    - secretKey: PG_USERNAME
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_USERNAME
    - secretKey: PG_DATABASE
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: PG_DATABASE
    - secretKey: INVENTORY_SERVICE_URL
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: INVENTORY_SERVICE_URL
    - secretKey: ORDER_SERVICE_URL
      remoteRef:
        key: RDS_DEV_CLUSTER_AUTH
        property: ORDER_SERVICE_URL