apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-secret
  namespace: crowdsec
spec:
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: crowdsec-env-secret
    creationPolicy: Owner
  data:
    - secretKey: ENROLL_KEY
      remoteRef:
        key: CROWDSEC_SECRET
        property: ENROLL_KEY
    - secretKey: ENROLL_INSTANCE_NAME
      remoteRef:
        key: CROWDSEC_SECRET
        property: ENROLL_INSTANCE_NAME
    - secretKey: ENROLL_TAGS
      remoteRef:
        key: CROWDSEC_SECRET
        property: ENROLL_TAGS